#!/bin/sh
### Start/Stop dynaTrace Host Agent daemon
#
# Copyright 2004-2012 dynaTrace Software
# All rights reserved.
#
# Copy this script to /etc/init.d and use chkconfig for enabling/disabling
# the daemon.
#
### BEGIN INIT INFO
# Provides: dynaTraceHostagent
# Required-Start: $network
# Required-Stop: $network
# X-UnitedLinux-Should-Start:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start/Stop dynaTrace Host Agent daemon
### END INIT INFO

# To use this file in your environment, adjusting the following variables:
# - DT_HOME     installation directory of dynaTrace software
# - DT_OPTARGS  optional arguments (server, ...)
DT_HOME=/tmp/j/dynatrace-6.0.0
DT_OPTARGS=

DT_PRODUCT="Host Agent"
DT_BINARY=dthostagent

DT_BINARY_WITH_PATH=$DT_HOME/agent/lib64/$DT_BINARY
DT_PIDFILE=/var/run/$DT_BINARY.pid
if [ ! -x "$DT_BINARY_WITH_PATH" ]; then
  DT_BINARY_WITH_PATH=$DT_HOME/agent/lib/$DT_BINARY
fi
if [ ! -x "$DT_BINARY_WITH_PATH" ]; then
  echo "File not found or not executable: $DT_BINARY_WITH_PATH"
  exit
fi
if [ -f "$DT_PIDFILE" ]; then
  PROCESSPID=`cat $DT_PIDFILE`
fi
if [ -z "$PROCESSPID" ]; then
  GREPARG=`echo $DT_BINARY | cut -c1-8`
  PROCESSPID=`ps -e | grep $GREPARG | awk '{{print $1}}'`
fi

case "$1" in
'start')
    nohup $DT_BINARY_WITH_PATH $DT_OPTARGS >/dev/null 2>&1 &
    ;;
'stop')
    if [ -n "$PROCESSPID" ]; then
      echo "Terminating dynaTrace $DT_PRODUCT process $PROCESSPID"
      kill -2 $PROCESSPID
    fi
    ;;
'status')
    if [ -n "$PROCESSPID" ]; then
      echo "dynaTrace $DT_PRODUCT daemon is running:"
      ps -ef | grep $DT_BINARY | grep $PROCESSPID
    else
      echo "dynaTrace $DT_PRODUCT daemon not running."
    fi
    ;;
*)
    echo "usage: $0 {start|stop|status}"
    ;;
esac
